wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.11.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.10
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      4: 3.7.10
      5: 0.11.0
      8:
      - 5
adaptive_reward:
  desc: null
  value: 'yes'
device:
  desc: null
  value: GPU
gen_data:
  desc: null
  value: ./random.smi
logP:
  desc: null
  value: 'no'
logP_threshold:
  desc: null
  value: 2.5
num_iterations:
  desc: null
  value: 175
predictor:
  desc: null
  value: dock
protein:
  desc: null
  value: 6LU7
qed:
  desc: null
  value: 'no'
qed_threshold:
  desc: null
  value: 0.8
remarks:
  desc: null
  value: ''
reward_function:
  desc: null
  value: exponential
seed:
  desc: null
  value: 0
solvation:
  desc: null
  value: 'no'
solvation_threshold:
  desc: null
  value: -10
switch:
  desc: null
  value: 'no'
switch_frequency:
  desc: null
  value: 35
tpsa:
  desc: null
  value: 'no'
tpsa_threshold:
  desc: null
  value: 100
use_checkpoint:
  desc: null
  value: 'yes'
use_wandb:
  desc: null
  value: 'yes'
